config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  resources :categories
  devise_for :users
  resources :posts
  get '/gallery', to: 'posts#gallery', as: :gallery
  get '/main', to: 'posts#main', as: :main
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#young'
end

app/views/shared/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://youngnigerian.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/shared/_footer.html.erb
<!-- FOOTER
================================================== -->
<footer class="section bg-dark">

  <!-- Triangles -->
  <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-left"></div>
  <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-right"></div>

  <!--Content -->
  <div class="container">
    <div class="row align-self-center">
      <div class="col-md-auto">

        <!-- Brand -->
        <p>
          <a href="#" class="footer-brand text-white">
              <h2>YN</h2>
          </a>
        </p>
    
      </div>
      <div class="col-md">
    
        <!-- Links -->
        <ul class="list-unstyled list-inline text-md-right">
          <li class="list-inline-item mr-2">
            <a href="#" class="text-white">
              Terms and conditions
            </a>
          </li>
          <li class="list-inline-item mr-2">
            <a href="#" class="text-white">
              Privacy policy
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#" class="text-white">
              Contact us
            </a>
          </li>
        </ul>

      </div>
    </div> <!-- / .row -->
    <div class="row align-items-center">
      <div class="col-md">
    
        <!-- Copyright -->
        <p class="text-white text-muted">
          <small>
            &copy; Copyright <span class="current-year"></span> YoungNigerian.com. All rights reserved.
          </small>
        </p>

      </div>
      <div class="col-md">
    
        <!-- Social links -->
        <!--<ul class="list-inline list-unstyled text-md-right">-->
        <!--  <li class="list-inline-item ml-3">-->
        <!--    <a href="#">-->
        <!--      <i class="fa fa-twitter fa-stack-1x"></i>-->
        <!--    </a>-->
        <!--  </li>-->
        <!--  <li class="list-inline-item ml-3">-->
        <!--    <a href="#">-->
        <!--    <i class="fa fa-instagram fa-stack-1x"></i>-->
        <!--    </a>-->
        <!--  </li>-->
        <!--</ul>-->

      </div>
    </div> <!-- / .row -->
  </div> <!-- / .container -->

</footer>

app/views/shared/_nav.html.erb
<!-- NAV
================================================== -->
<div class="mt-navbar border-bottom">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-md-auto">
        <nav class="nav nav-overflow py-2">
          <!--<p class= "nav-link font-weight-normal text-xs">Your one stop online place</p><br>-->
          <%# @catSections.each do |category| %>
            <%#= link_to category.name, category_path(category.id), class: "nav-link font-weight-normal text-xs" %>
          <%# end %>
            <%= link_to "TV", root_path, class: "nav-link font-weight-normal text-xs" %>
            <%#= link_to "Awards", root_path, class: "nav-link font-weight-normal text-xs" %>
            <%= link_to "Music", root_path, class: "nav-link font-weight-normal text-xs" %>
            <%= link_to "MarketPlace", root_path, class: "nav-link font-weight-normal text-xs" %>
            <%= link_to "About Us", root_path, class: "nav-link font-weight-normal text-xs" %>
            <%#= link_to "IYEE", root_path, class: "nav-link font-weight-normal text-xs" %>
        </nav>
      </div>
    </div> <!-- / .row -->
  </div> <!-- / .container -->
</div>

app/views/shared/_navbar.html.erb
<!-- NAVBAR -->
<nav class="navbar navbar-expand-xl navbar-dark  navbar-togglable  fixed-top">
  <div class="container">

    <!-- Brand -->
    <%= link_to "YN", root_path, class: "navbar-brand"%>
    <!--<a class="navbar-brand" href="index.html">-->
    <!--  <h2 style="color: white;">Young</h2>-->
  
      <!--<svg class="navbar-brand-svg" viewBox="0 0 245 80" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">-->
      <!--  <path d="M0 0 L 20 10 L 0 20 Z" class="navbar-brand-svg-i" fill="currentColor"></path>-->
      <!--  <path d="M0 30 L 20 40 L 0 50 Z M20 45 L 0 55 L 20 65 Z M0 60 L 20 70 L 0 80 Z" fill="currentColor"></path>-->
      <!--  <text x="40" y="70" font-family="Arial, sans-serif" font-size="60" font-weight="bold" letter-spacing="-.025em" fill="currentColor">incline.</text>-->
      <!--</svg>-->
    <!--</a>-->

    <!-- Toggler -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbarCollapse">

      <!-- Social -->
      <ul class="navbar-nav mr-auto">
        <li class="nav-item-divider">
          <span class="nav-link">
            <span></span>
          </span>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="fa fa-twitter fa-stack-1x"></i>
            <span class="d-xl-none ml-2">
              Twitter
            </span>
          </a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="fa fa-instagram fa-stack-1x"></i>
            <span class="d-xl-none ml-2">
              Instagram
            </span>
          </a>
        </li>
      </ul>

      <!-- Links -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <%= link_to "Home", root_path, class: "nav-link"%>
          <!--<a class="nav-link" href="#" id="navbarWelcome" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <!--  Home-->
          <!--</a>-->
          <!--<div class="dropdown-menu" aria-labelledby="navbarWelcome">-->
          <!--  <a class="dropdown-item  active " href="#">-->
          <!--    Header: Image-->
          <!--  </a>-->
          <!--  <a class="dropdown-item " href="#">-->
          <!--    Header: Carousel-->
          <!--  </a>-->
          <!--  <a class="dropdown-item " href="#">-->
          <!--    Header: Parallax-->
          <!--  </a>-->
          <!--  <a class="dropdown-item " href="#">-->
          <!--    Header: Video-->
          <!--  </a>-->
          <!--</div>-->
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarLandings" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Features
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarLandings">
            <% @catSections.each do |category| %>
              <%= link_to category.name, category_path(category.id), class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
        <%# @catSections.each do |category| %>
          <!--<li class="nav-item dropdown">-->
            <%#= link_to category.name, category_path(category.id), class: "nav-link" %>
          <!--</li>-->
        <%# end %>
        <li class="nav-item-divider">
          <span class="nav-link">
            <span></span>
          </span>
        </li>
        <li class="nav-item">
          <a href="#" target="_blank" class="nav-link">
            Contact Us
          </a>
        </li>
        
        </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <%#= 'Logged in as ' current_user.email, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_registration_path, :class => 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'nav-link'  %>
            </li>
            <% else %>
              <%#= link_to "Sign up", new_user_registration_path, :class => 'nav-link font-weight-normal text-xs'  %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class => 'nav-link'  %>
            </li>  
            <% end %>
          <!--<a href="#" target="_blank" class="nav-link">-->
          <!--  Others-->
          <!--</a>-->
        </li>
      </ul>

    </div> <!-- / .navbar-collapse -->

  </div> <!-- / .container -->    
</nav>













<!--<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--  <%#= link_to "Jerry's Site", root_path, class: "navbar-brand" %>-->
<!--  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">-->
<!--    <span class="navbar-toggler-icon"></span>-->
<!--  </button>-->
<!--  <div class="collapse navbar-collapse" id="navbarText">-->
<!--    <ul class="navbar-nav mr-auto">-->
<!--      <%# @catSections.each do |category| %>-->
<!--        <li class="nav-item active">-->
<!--          <%#= link_to category.name, category_path(category.id), class: "nav-link" %>-->
<!--        </li>-->
        
<!--        <li class="nav-item active">-->
<!--          <%#= link_to 'Gallery', gallery_path, class: "nav-link" %>-->
<!--        </li>-->
<!--      <%# end %>-->
<!--    </ul>-->
<!--    <span class="navbar-text">-->
<!--      <%# if user_signed_in? %>-->
<!--        Logged in as <strong><%#= current_user.email %></strong>-->
<!--        <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |-->
<!--        <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>-->
<!--      <%# else %>-->
<!--        <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |-->
<!--        <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>-->
<!--      <%# end %>-->
<!--     </span>-->
<!--  </div>-->
<!--</nav>-->

app/views/shared/_newsletter.html.erb
<!-- NEWSLETTER
================================================== -->
<section class="section bg-light">

  <!-- Line -->
  <div class="line line-top"></div>

  <!-- Triangles -->
  <div class="bg-triangle bg-triangle-light bg-triangle-top bg-triangle-left"></div>
  <div class="bg-triangle bg-triangle-light bg-triangle-bottom bg-triangle-right"></div>

  <!-- Content -->
  <div class="container">
    <div class="row">
      <div class="col">
        
        <!-- Heading -->
        <h3 class="text-center mb-5">
          Sign up to our newsletter
        </h3>

        <!-- Form -->
        <form class="form-mailchimp validate" action="..." method="get" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" target="_blank" novalidate="">
          <div id="mc_embed_signup_scroll" class="form-row justify-content-center">
            <div class="input-group col-md-4 mb-2 mb-md-0">
              <input type="email" value="" name="EMAIL" class="required email form-control bg-white order-1" id="mce-EMAIL" placeholder="Email address">
              <div class="input-group-append order-0">
                <div class="input-group-text bg-white">
                  <svg class="icon icon-envelope input-group-icon icon-offset" viewBox="0 0 106 106" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                    <path transform="translate(3 3)" d="
                      M0 30 V 10 H 100 V 90 H 0 V 30 L 50 60 L 100 30">
                    </path>
                  </svg>
                </div>
              </div>
              <div id="mce-responses" class="clear">
                <div class="response"></div>
                <div class="response" id="mce-success-response"></div>
              </div>
              <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
              <div aria-hidden="true" id="mce-hidden-input">
                <input type="text" name="b_507744bbfd1cc2879036c7780_4523d25e1b" tabindex="-1" value="">
              </div>
            </div>
            <div class="clear col-md-auto">
              <button type="submit" class="btn btn-outline-primary bg-white btn-block btn-md-auto" id="mc-embedded-subscribe">
                Sign up
              </button>
            </div>
          </div>
        </form>

      </div>
    </div> <!-- / .row -->
  </div> <!-- / .container -->

</section>

<script type="text/javascript" src="//downloads.mailchimp.com/js/signup-forms/popup/unique-methods/embed.js" data-dojo-config="usePlainJson: true, isDebug: false"></script><script type="text/javascript">window.dojoRequire(["mojo/signup-forms/Loader"], function(L) { L.start({"baseUrl":"mc.us20.list-manage.com","uuid":"0b4eb7d0dec6f7a8d2b9f62ba","lid":"179d512ca7","uniqueMethods":true}) })</script>