config/routes.rb
Rails.application.routes.draw do
  resources :adverts
  resources :categories
  devise_for :users
  resources :posts
  get '/gallery', to: 'posts#gallery', as: :gallery
  get '/main', to: 'posts#main', as: :main
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#young'
end

app/models/advert.rb
class Advert < ApplicationRecord
    
  mount_uploader :image, ImageUploader
  
  enum status: { low: 0, medium: 1, high: 2, veryhigh:3 }
  
end

app/controllers/adverts_controller.rb
class AdvertsController < ApplicationController
  before_action :set_advert, only: [:show, :edit, :update, :destroy]

  # GET /adverts
  # GET /adverts.json
  def index
    @adverts = Advert.all
  end

  # GET /adverts/1
  # GET /adverts/1.json
  def show
  end

  # GET /adverts/new
  def new
    @advert = Advert.new
  end

  # GET /adverts/1/edit
  def edit
  end

  # POST /adverts
  # POST /adverts.json
  def create
    @advert = Advert.new(advert_params)

    respond_to do |format|
      if @advert.save
        format.html { redirect_to @advert, notice: 'Advert was successfully created.' }
        format.json { render :show, status: :created, location: @advert }
      else
        format.html { render :new }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adverts/1
  # PATCH/PUT /adverts/1.json
  def update
    respond_to do |format|
      if @advert.update(advert_params)
        format.html { redirect_to @advert, notice: 'Advert was successfully updated.' }
        format.json { render :show, status: :ok, location: @advert }
      else
        format.html { render :edit }
        format.json { render json: @advert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adverts/1
  # DELETE /adverts/1.json
  def destroy
    @advert.destroy
    respond_to do |format|
      format.html { redirect_to adverts_url, notice: 'Advert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advert
      @advert = Advert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advert_params
      params.require(:advert).permit(:title, :image, :url, :status, :desc)
    end
end

app/helpers/adverts_helper.rb
module AdvertsHelper
end

app/views/adverts/_form.html.erb
<%= form_with(model: advert, local: true) do |form| %>
  <% if advert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(advert.errors.count, "error") %> prohibited this advert from being saved:</h2>

      <ul>
      <% advert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, Advert.statuses.map { |key, value| [key.humanize, key] } %>
  </div>

  <div class="field">
    <%= form.label :desc %>
    <%= form.text_field :desc %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/adverts/edit.html.erb
<h1>Editing Advert</h1>

<%= render 'form', advert: @advert %>

<%= link_to 'Show', @advert %> |
<%= link_to 'Back', adverts_path %>

app/views/adverts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Adverts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Image</th>
      <th>Url</th>
      <th>Status</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adverts.each do |advert| %>
      <tr>
        <td><%= advert.title %></td>
        <td><%= image_tag(advert.image.url, alt: 'Image', class: "card-img") if advert.image? %></td>
        <!--<td><%#= advert.image %></td>-->
        <td><%= advert.url %></td>
        <td><%= advert.status %></td>
        <td><%= advert.desc %></td>
        <td><%= link_to 'Show', advert %></td>
        <td><%= link_to 'Edit', edit_advert_path(advert) %></td>
        <td><%= link_to 'Destroy', advert, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Advert', new_advert_path %>

app/views/adverts/new.html.erb
<h1>New Advert</h1>

<%= render 'form', advert: @advert %>

<%= link_to 'Back', adverts_path %>

app/views/adverts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @advert.title %>
</p>

<p>
  <strong>Image:</strong>
  <%= @advert.image %>
</p>

<p>
  <strong>Url:</strong>
  <%= @advert.url %>
</p>

<p>
  <strong>Status:</strong>
  <%= @advert.status %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @advert.desc %>
</p>

<%= link_to 'Edit', edit_advert_path(@advert) %> |
<%= link_to 'Back', adverts_path %>